stages:
  - build
  - test
  - deploy

bundle:
  script:
  - bundle install -j $(nproc)
  stage: build

rspec:
  script:
  - cp test/app/config/database.test.yml test/app/config/database.yml
  - sed "s/_test/_test_$CI_BUILD_ID/" -i test/app/config/database.yml
  - bundle exec rake db:create db:migrate
  - bundle exec rspec
  stage: test

rubocop:
  script:
  - bundle exec rubocop
  stage: test

brakeman:
  script:
  - bundle exec brakeman -w3 --exit-on-warn
  stage: test
